---
title: "Week 1 Exercizes"
author: "Luke Tuttle"
date: "5/16/18"
output: "pdf_document"
---

This is an R Markdown of the exercizes assigned for week 1 of R training at Sorneson Impact Center. 


```{r, setup, include=FALSE}

library(tidyverse)
library(knitr)
library(forcats)
library(readxl)
library(lubridate)

```



Tables 1-7
```{r, tables}



mtcars %>% 
  group_by(gear) %>% 
  summarize(n = n())

mtcars %>% 
  group_by(carb) %>% 
  summarize(n = n())

#Create a table of vs
#Create a table of am

#tables of cyl by "x" 
with(mtcars,table(gear, cyl))

with(mtcars,table(am, cyl))

with(mtcars,table(vs, cyl))

```


Histograms of wt, mpg, qsec, and hp. 
```{r, histograms}
#histogram of wt
ggplot(mtcars, aes(x = wt)) +
  geom_histogram(binwidth = .25)

#histogram of mpg
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 3)

#histogram of qsec
ggplot(mtcars, aes(x = qsec)) +
  geom_histogram(binwidth = 0.5)

#histogram of hp
ggplot(mtcars, aes(x = hp)) +
  geom_histogram(binwidth = 25)

```

Mean mpg by cylinder 
```{r, mean_mpg_by_cyl}

mtcars %>%
  group_by(cyl) %>% 
  summarize(meanmpg = mean(mpg))

#graph
mtcars %>%
  group_by(cyl) %>% 
  summarize(meanmpg = mean(mpg)) %>% 
ggplot(aes(x = cyl, y = meanmpg)) + 
    geom_col()

```

Mean weight by cylinder
```{r, wt_by_cyl}

wt_cyl <- mtcars %>%
  group_by(cyl) %>% 
  summarize(meanwt = mean(wt))

ggplot(wt_cyl, aes(x = cyl, y = meanwt)) +
  geom_col(width = 1)

```

Mean horsepower by cylinder
```{r, hp_by_cyl}

meanhp_cyl <- mtcars %>% 
  group_by(cyl) %>% 
  summarize(meanhp = mean(hp))

ggplot(meanhp_cyl, aes(x = cyl, y = meanhp)) +
  geom_col(width = 1)
```
